// static/frontend/reddit-app/src/app/auth/sign-up/sign-up.component.ts
import { AfterViewInit, Component, OnInit, } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { UserService } from '@reddit/core/services/user/user.service';
import { MatSnackBar } from '@angular/material/snack-bar';


@Component({
  selector: 'app-sign-up',
  templateUrl: './sign-up.component.html',
  styleUrls: ['./sign-up.component.scss']
})
export class SignUpComponent implements OnInit {
  registerForm: FormGroup;
  isLoading: boolean = false;
  hidePassword: boolean = true;
  errors = [];

  constructor(
    private userService: UserService,
    private router: Router,
    private snackbar: MatSnackBar
  ) { }

  ngOnInit(): void {
    this.registerForm = new FormGroup({
      first_name: new FormControl('', {
        validators: [Validators.required]
      }),
      last_name: new FormControl('', {
        validators: [Validators.required]
      }),
      email: new FormControl('', {
        validators: [Validators.required, Validators.email]
      }),
      password1: new FormControl('', { validators: [Validators.required] }),
      password2: new FormControl('', { validators: [Validators.required] })
    });
  }

  toggleVisibility() {
    this.hidePassword = !this.hidePassword;
  }

  onSubmit() {
    const formData = {
      first_name: this.registerForm.value.first_name,
      last_name: this.registerForm.value.last_name,
      email: this.registerForm.value.email,
      password1: this.registerForm.value.password1,
      password2: this.registerForm.value.password2
    };
    this.isLoading = true;
    this.userService.register(formData).subscribe(
      (result) => {
        this.isLoading = false;
        this.registerForm.reset();
        this.snackbar.open('Registered successfully. Proceed to login');
        this.router.navigate(['sign-in']);
      },
      (err) => {
        this.isLoading = false;
        // console.log(err.error);
      }
    );
  }
}

<div class="auth-container">
  <div class="login-form">
    <h2 class="text-white" align="center">Sign up for Django-Reddit </h2>

    <form class="width-100" [formGroup]="registerForm" class="auth-form" autocomplete="off">
      <div class="input-column" style="display: flex; gap: 16px">
        <div class="width-100 margin-bottom-4">
          <label for="email">First name</label>
          <input matInput placeholder="John" formControlName="first_name" type="text" class="form-input">
        </div>

        <div class="width-100 margin-bottom-4">
          <label for="email">Last name</label>
          <input matInput placeholder="Doe" formControlName="last_name" type="text" class="form-input">
        </div>
      </div>

      <div class="width-100 margin-bottom-4">
        <label for="email">Email</label>
        <input matInput placeholder="jane@email.com" formControlName="email" type="email" class="form-input">
      </div>

      <div class="input-column margin-bottom-4" style="display: flex; gap: 16px; position: relative">
        <div class="width-100">
          <label for="password">Password</label>
          <input matInput placeholder="dankworld12" formControlName="password1" [type]="hidePassword ? 'password' : 'text'" class="form-input">
          <button mat-icon-button matSuffix class="toggle-visibility-btn" (click)="toggleVisibility()" [attr.aria-label]="'Hide password'" [attr.aria-pressed]="hidePassword">
            <mat-icon>{{hidePassword ? 'visibility_off' : 'visibility'}}</mat-icon>
          </button>
        </div>

        <div class="width-100">
          <label for="password">Confirm password</label>
          <input matInput placeholder="dankworld12" formControlName="password2" [type]="hidePassword ? 'password' : 'text'" class="form-input">
          <button mat-icon-button matSuffix class="toggle-visibility-btn" (click)="toggleVisibility()" [attr.aria-label]="'Hide password'" [attr.aria-pressed]="hidePassword">
            <mat-icon>{{hidePassword ? 'visibility_off' : 'visibility'}}</mat-icon>
          </button>
        </div>
      </div>

      <button mat-button color="primary" class="width-100 custom-button block-button"
        [disabled]="!registerForm.valid || isLoading" (click)="onSubmit()" >Submit</button>

      <p>Already have an account? <a class="underline button-link" [routerLink]="['../sign-in']">Sign In</a></p>

    </form>
  </div>
</div>

// static/frontend/reddit-app/react-app/src/components/auth/SignUp/SignUp.tsx
import React, { useState } from 'react';
import './SignUp.scss';

const SignUp = () => {
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [hidePassword, setHidePassword] = useState(true);

  const toggleVisibility = () => {
    setHidePassword(!hidePassword);
  };

  const onSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (password !== confirmPassword) {
      alert("Passwords don't match");
      return;
    }
    const signUpData = {
      first_name: firstName,
      last_name: lastName,
      email,
      password,
    };
    setIsLoading(true);
    // Placeholder for userService.register
    console.log('Signing up with:', signUpData);
    setTimeout(() => {
      setIsLoading(false);
      // Placeholder for snackbar
      alert('Successfully signed up');
      // router.navigate(['/sign-in']);
    }, 1000);
  };

  return (
    <div className="auth-container">
      <div className="login-form">
        <h2 className="text-white" style={{ textAlign: 'center' }}>Sign up for Django-Reddit</h2>

        <form className="width-100 auth-form" autoComplete="off" onSubmit={onSubmit}>
          <div className="input-column" style={{ display: 'flex', gap: '16px' }}>
            <div className="width-100 margin-bottom-4">
              <label htmlFor="firstname">First name</label>
              <input
                id="firstname"
                placeholder="John"
                type="text"
                className="form-input"
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
                required
              />
            </div>

            <div className="width-100 margin-bottom-4">
              <label htmlFor="lastname">Last name</label>
              <input
                id="lastname"
                placeholder="Doe"
                type="text"
                className="form-input"
                value={lastName}
                onChange={(e) => setLastName(e.target.value)}
                required
              />
            </div>
          </div>

          <div className="width-100 margin-bottom-4">
            <label htmlFor="email">Email</label>
            <input
              id="email"
              placeholder="jane@email.com"
              type="email"
              className="form-input"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </div>

          <div className="input-column margin-bottom-4" style={{ display: 'flex', gap: '16px', position: 'relative' }}>
            <div className="width-100">
              <label htmlFor="password">Password</label>
              <input
                id="password"
                placeholder="dankworld12"
                type={hidePassword ? 'password' : 'text'}
                className="form-input"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
              <button type="button" className="toggle-visibility-btn" onClick={toggleVisibility} aria-label="Hide password" aria-pressed={hidePassword}>
                {hidePassword ? 'visibility_off' : 'visibility'}
              </button>
            </div>

            <div className="width-100">
              <label htmlFor="confirmPassword">Confirm password</label>
              <input
                id="confirmPassword"
                placeholder="dankworld12"
                type={hidePassword ? 'password' : 'text'}
                className="form-input"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                required
              />
              <button type="button" className="toggle-visibility-btn" onClick={toggleVisibility} aria-label="Hide password" aria-pressed={hidePassword}>
                {hidePassword ? 'visibility_off' : 'visibility'}
              </button>
            </div>
          </div>

          <button
            type="submit"
            className="width-100 custom-button block-button"
            disabled={!firstName || !lastName || !email || !password || !confirmPassword || isLoading}
          >
            {isLoading ? 'Loading...' : 'Submit'}
          </button>

          <p>Already have an account? <a className="underline button-link" href="../sign-in">Sign In</a></p>
        </form>.
      </div>
    </div>
  );
};

export default SignUp;
