// static/frontend/reddit-app/react-app/src/components/auth/SignIn/SignIn.tsx
import React, { useState } from 'react';
import './SignIn.scss';

const SignIn = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [hidePassword, setHidePassword] = useState(true);

  const toggleVisibility = () => {
    setHidePassword(!hidePassword);
  };

  const onSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const loginData = {
      email,
      password
    };
    setIsLoading(true);
    // Placeholder for userService.login
    console.log('Logging in with:', loginData);
    setTimeout(() => {
      setIsLoading(false);
      // Placeholder for snackbar
      alert('Successfully logged in');
      // router.navigate(['']);
    }, 1000);
  };

  return (
    <div className="auth-container">
      <div className="login-form">
        <h2 className="text-white" style={{ textAlign: 'center' }}>Sign in to Django Reddit</h2>

        <div className="buttons-section">
          <button className="custom-button" disabled style={{ borderColor: 'rgb(255, 92, 136)' }}>Google</button>
          <button className="custom-button" disabled style={{ borderColor: 'rgb(255, 192, 93)' }}>Facebook</button>
        </div>

        <div className="separator-section">
          <div className="divider-left"></div>
          <p style={{ textAlign: 'center' }}>OR</p>
          <div className="divider-right"></div>
        </div>

        <form className="width-100 auth-form" autoComplete="off" onSubmit={onSubmit}>
          <div className="width-100 margin-bottom-4">
            <label htmlFor="email">Email</label>
            <input
              id="email"
              placeholder="jane@email.com"
              type="email"
              className="form-input"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>

          <div className="width-100 margin-bottom-4" style={{ position: 'relative' }}>
            <label htmlFor="password">Password</label>
            <input
              id="password"
              placeholder="wonderfullemon dankworld"
              type={hidePassword ? 'password' : 'text'}
              className="form-input"
              required
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <button type="button" className="toggle-visibility-btn" onClick={toggleVisibility} aria-label="Hide password" aria-pressed={hidePassword}>
              {hidePassword ? 'visibility_off' : 'visibility'}
            </button>
          </div>

          <button type="submit" className="margin-top-4 width-100 custom-button block-button submit-button" disabled={!email || !password || isLoading}>
            {isLoading ? 'Loading...' : 'Submit'}
          </button>

          <p>Haven't registered yet? <a className="underline button-link" href="../sign-up">Sign Up</a></p>
        </form>
      </div>
    </div>
  );
};

export default SignIn;

// static/frontend/reddit-app/src/app/auth/sign-in/sign-in.component.ts
import { AfterViewInit, Component, OnInit, } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { UserService } from '@reddit/core/services/user/user.service';
import { MatSnackBar } from '@angular/material/snack-bar';


@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.scss']
})
export class SignInComponent implements OnInit {
  loginForm: FormGroup;
  isLoading: boolean = false;
  hidePassword: boolean = true;

  constructor(
    private userService: UserService,
    private router: Router,
    private snackbar: MatSnackBar
  ) { }

  ngOnInit(): void {
    this.loginForm = new FormGroup({
      email: new FormControl('', {
        validators: [Validators.required, Validators.email]
      }),
      password: new FormControl('', { validators: [Validators.required] })
    });
  }

  toggleVisibility() {
    this.hidePassword = !this.hidePassword;
  }

  onSubmit() {
    const loginData = {
      email: this.loginForm.value.email,
      password: this.loginForm.value.password
    };
    this.isLoading = true;
    this.userService.login(loginData).subscribe(
      (result) => {
        this.isLoading = false;
        this.snackbar.open('Successfully logged in');
        this.router.navigate(['']);
      },
      (err) => {
        this.isLoading = false;
        // console.log(err.error);
      }
    );
  }

}

<div class="auth-container">
  <div class="login-form">
    <h2 class="text-white" align="center">Sign in to Django Reddit </h2>

      <div class="buttons-section">
        <button mat-button class="custom-button" (click)="onSubmit()" style="border-color: rgb(255, 92, 136)" disabled>Google</button>
        <button mat-button class="custom-button" (click)="onSubmit()" style="border-color: rgb(255, 192, 93)" disabled>Facebook</button>
      </div>

      <div class="separator-section">
        <div class="divider-left"></div>
        <p align="center">OR</p>
        <div class="divider-right"></div>
      </div>

      <form class="width-100" [formGroup]="loginForm" class="auth-form" autocomplete="off">
        <div class="width-100 margin-bottom-4">
          <label for="email">Email</label>
          <input matInput id="email" placeholder="jane@email.com" formControlName="email" type="email" class="form-input" required>
        </div>

        <div class=""></div>

        <div class="width-100 margin-bottom-4" style="position: relative">
          <label for="password">Password</label>
          <input matInput id="password" placeholder="wonderfullemon dankworld" formControlName="password" [type]="hidePassword ? 'password' : 'text'" class="form-input" required>
          <button mat-icon-button matSuffix class="toggle-visibility-btn" (click)="toggleVisibility()" [attr.aria-label]="'Hide password'" [attr.aria-pressed]="hidePassword">
            <mat-icon>{{ hidePassword ? 'visibility_off' : 'visibility' }}</mat-icon>
          </button>
        </div>

        <button mat-button color="primary" (click)="onSubmit()" class="margin-top-4 width-100 custom-button block-button submit-button" [disabled]="!loginForm.valid">
          Submit
        </button>


        <p>Haven't registered yet? <a class="underline button-link" [routerLink]="['../sign-up']">Sign Up</a></p>
      </form>
  </div>
</div>
