// static/frontend/reddit-app/src/app/auth/sign-out/sign-out.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-sign-out',
  templateUrl: './sign-out.component.html',
  styleUrls: ['./sign-out.component.scss']
})
export class SignOutComponent implements OnInit {
  fragment: string;
  context: any;

  redirection = {
    'delete' : {
      title: 'You will be missed ;(',
      subtitle: `Your account shall be permanently deleted in 14 days.
        If you change your mind, please send us a request mail at admin@gmail.com
        and we shall set-up everything just like it was before.. `
    },
    'deactivate' : {
      title: 'You will be missed ;(',
      subtitle: `Whenever you wish to reactivate your account,
      please send us a request mail at admin@gmail.com and we shall set-up
      everything just like it was before.`
    }
  }

  constructor(
    private route: ActivatedRoute
  ) { }

  ngOnInit(): void {
    this.route.fragment.subscribe((fragment: string) => {
        this.fragment = fragment;
        this.context = this.redirection[this.fragment]
    })

    setTimeout(() => {
      window.open(`${environment.appUrl}`, '_self')
    }, 3000);
  }
}

<ng-container>
  <div fxLayout="column" class="message-container width-100 height-100">
    <p class="font-bold width-100 text-center container-title">{{ context.title }}</p>
    <p class="font-sm text-center width-100 container-subtitle">
      {{ context.subtitle }}
    </p>
  </div>
</ng-container>

// static/frontend/reddit-app/react-app/src/components/auth/SignOut/SignOut.tsx
import React, { useEffect, useState } from 'react';
import './SignOut.scss';

const SignOut = () => {
  const [context, setContext] = useState({ title: '', subtitle: '' });
  const redirection: any = {
    'delete' : {
      title: 'You will be missed ;(',
      subtitle: `Your account shall be permanently deleted in 14 days.
        If you change your mind, please send us a request mail at admin@gmail.com
        and we shall set-up everything just like it was before.. `
    },
    'deactivate' : {
      title: 'You will be missed ;(',
      subtitle: `Whenever you wish to reactivate your account,
      please send us a request mail at admin@gmail.com and we shall set-up
      everything just like it was before.`
    }
  }
  useEffect(() => {
    const fragment = window.location.hash.substring(1);
    if (fragment && redirection[fragment]) {
      setContext(redirection[fragment]);
    }

    setTimeout(() => {
      window.open('/', '_self')
    }, 3000);
  }, []);

  return (
    <div className="message-container width-100 height-100">
      <p className="font-bold width-100 text-center heading-1">{context.title}</p>
      <p className="font-sm text-center width-100 heading-3">
        {context.subtitle}
      </p>
    </div>
  );
};

export default SignOut;
